### ISSUE TITLE
Want to download the source code

### ISSUE THREAD

**Issue by dahaigui** [cvlab-columbia/pix2gestalt#1]
We are doing agricultural research, the crop will be more folded when growing in the field, so we need to use algorithms that can segment the shaded part, I noticed your project, and would like to take the source code and try it out to see if it can be applied to our agricultural research!

**Comment by egeozguroglu** [comment]
Hi, thanks for your interest! Our code will be released next week.

**Comment by dahaigui** [comment]
That's definitely wonderful information, looking forward to it!

**Comment by CHN-001** [comment]
looking forward to your code! I want to apply it to my research!

**Comment by 591582523h** [comment]
looking forward to your code!

**Comment by RunpuWei** [comment]
looking forward to your code!

**Comment by egeozguroglu** [comment]
Hi all, our code has been released!

**Comment by dahaigui** [comment]
> Hi all, our code has been released!

What a wonderful message!
