### ISSUE TITLE
How long does it take to train each epoch?

### ISSUE THREAD

**Issue by liuzc1999** [cvlab-columbia/pix2gestalt#10]
Hi, I'm very impressed with your solid work, while I feel curious that how much time is needed to train each epoch and how many epochs may be enough for a competent model. Looking forward to your reply, thanks.

**Comment by egeozguroglu** [comment]
Hi! Thanks for your interest in our paper. Our default checkpoint is trained for 5 epochs on 8 A100 GPUs. One epoch takes around 2 hours.
