### ISSUE TITLE
Raw images before pasting foreground objects

### ISSUE THREAD

**Issue by zhyever** [cvlab-columbia/pix2gestalt#13]
Thanks for your amazing work! I was wondering if it would be possible that you also release the raw images before pasting the foreground objects. Or would it be possible that we can use some strategies to find that corresponding raw images from the current SAM-1B dataset?

Also, could you please share the code for foreground check? It could be very helpful. Thanks.

**Comment by zhyever** [comment]
The id is exactly the same as the raw sam-1b dataset

**Comment by egeozguroglu** [comment]
Thanks for your interest in our paper. Correct, you can use the SA-1B IDs directly.

**Comment by zhyever** [comment]
Hi, I would like to ask if it is possible to also get the foreground object's mask as well? I believe it will make method comparison much easier and make this dataset more popular in various vision tasks! Thanks for your help.

**Comment by egeozguroglu** [comment]
Hi, I'll look into this & get back to you!

**Comment by egeozguroglu** [comment]
Unfortunately, we haven't stored the occluder mask indices. As the SA-1B dataset is already SAM generated, it is straightforward to retrieve them by prompting SAM.
