### ISSUE TITLE
How can I make my custom dataset?

### ISSUE THREAD

**Issue by binh0804** [cvlab-columbia/pix2gestalt#14]
I am working on recovery occluded/broken crystal in microscope image, so I want to make a dataset on my own. Does it have any tool to crate annotations for pix2gestalt ?

**Comment by egeozguroglu** [comment]
Hi, we do not provide a tool to create manual annotations -- as our dataset of occlusions and their whole counterparts is created automatically. However, so long as you follow the format of our open-sourced dataset, you can follow the training script and instructions to train (from Image-conditioned SD weights) or fine-tune (from pix2gestalt weights) our model on your own dataset.
