### ISSUE TITLE
如果要制作自己的数据集应该是什么格式的，coco格式的可以训练吗？

### ISSUE THREAD

**Issue by Wyatt823** [cvlab-columbia/pix2gestalt#15]

**Comment by egeozguroglu** [comment]
Hi, if I translated your question correctly: the format needs to match [our released dataset](https://github.com/cvlab-columbia/pix2gestalt?tab=readme-ov-file#dataset). Note that COCO or Amodal COCO formats don't have amodal (whole) target images, which you need to perform amodal completion. After you replicate this format, you can directly use our fine-tuning [script](https://github.com/cvlab-columbia/pix2gestalt?tab=readme-ov-file#dataset) on your custom dataset.

**Comment by Wyatt823** [comment]
非常感谢您的回答，请问执行amodal是指 amodal completion这一步吗？如图所示，我需要对自己的数据集进行 novel view synthesis and 3D reconstruction,， use SyncDreamer？
![image](https://github.com/cvlab-columbia/pix2gestalt/assets/127301551/ba08c41b-44c0-4ff4-9bd3-26df09d514e2)
