### ISSUE TITLE
Inference doesn't run on cpu only device

### ISSUE THREAD

**Issue by JDups** [cvlab-columbia/pix2gestalt#16]
Attempting to run `inference.run_inference()` with `device='cpu'` on a Google colab CPU only instance produces an error.

`RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

I worked around this by commenting out lines 30 to 32 of /ldm/models/diffusion/ddim.py. I am not sure if this will cause problems elsewhere that I haven't noticed.

**Comment by egeozguroglu** [comment]
Hi, we haven't tested on CPU-based inference or Google Colab, given the compute requirements. Your solution should be fine as a workaround.
