### ISSUE TITLE
如何在多个GPU上进行推理

### ISSUE THREAD

**Issue by Wyatt823** [cvlab-columbia/pix2gestalt#17]
在执行推理时，发现只能在单GPU进行，但是单个GPU的显存太小

**Comment by egeozguroglu** [comment]
Hi, thanks for the interest in our work. What's the issue here?

**Comment by Wyatt823** [comment]
如何在使用多个GPU进行推理

**Comment by ThePassedWind** [comment]
> 如何在使用多个GPU进行推理

+1

**Comment by egeozguroglu** [comment]
Hi, if I translated your question correctly, you'll need to modify the Gradio demo with data parallel to support multiple GPUs. The released version is for one GPU.
