### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by liuzc1999** [cvlab-columbia/pix2gestalt#21]
Hi, I appreciate your inspiring work, but something confusing occurred. I tried to evaluate your released model on the Amodal COCO dataset using 'inference.py', but got lower performance. The mIoU results of the three experiments were 76.90, 77.57, and 77.74 respectively. Could you help me find what else needs to be added in the pipeline?

**Comment by egeozguroglu** [comment]
Hi, please refer to https://github.com/cvlab-columbia/pix2gestalt/issues/19. Feel free to email us for any specific scripts for Amodal COCO & BSDS amodal segmentation evaluation, or for recognition / 3D.

**Comment by liuzc1999** [comment]
Hi Ozguroglu, thanks for your response. About 10 days ago, I sent you an email for the evaluation scripts, but got no reply. I'd like to kindly inquire if you had the chance to review my previous message. I would greatly appreciate your assistance.
![WeChat6034ecfacf5c789d5952b8eda521230a](https://github.com/user-attachments/assets/149e55fa-5fde-492f-8f18-1a9b68108b8e)
