### ISSUE TITLE
此模型用的主干网络是什么？

### ISSUE THREAD

**Issue by Wyatt823** [cvlab-columbia/pix2gestalt#22]

**Comment by egeozguroglu** [comment]
Hi, thanks for the interest in our work! I tried to translate, but could you elaborate on the issue in English please -- so we can help? Thank you.

**Comment by Wyatt823** [comment]
hi，What is the backbone network used for this model?Do you use the ddim network？Thank you for your answer

**Comment by egeozguroglu** [comment]
We use an image-conditioned latent diffusion model (LDM) and fine-tune it on our dataset, from Stable Diffusion pre-training weights. The backbone components are [DDPM](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/ldm/models/diffusion/ddpm.py) and [DDIM](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/ldm/models/diffusion/ddim.py), correct.

**Comment by egeozguroglu** [comment]
Also, more details are provided in our [paper](https://arxiv.org/abs/2401.14398).
