### ISSUE TITLE
For the evaluation scripts

### ISSUE THREAD

**Issue by liuzc1999** [cvlab-columbia/pix2gestalt#24]
Hi Ozguroglu, thanks for your response. About 10 days ago, I sent you an email for the evaluation scripts, but got no reply. I'd like to kindly inquire if you had the chance to review my previous message. I would greatly appreciate your assistance.
![WeChat6034ecfacf5c789d5952b8eda521230a](https://github.com/user-attachments/assets/149e55fa-5fde-492f-8f18-1a9b68108b8e)

_Originally posted by @liuzc1999 in https://github.com/cvlab-columbia/pix2gestalt/issues/21#issuecomment-2337506435_

**Comment by egeozguroglu** [comment]
Hi, sorry for the delay! I will respond there by the end of this week, latest.
