### ISSUE TITLE
Issue with Frontend Error While Running pix2gestalt

### ISSUE THREAD

**Issue by automate11** [cvlab-columbia/pix2gestalt#25]
,

The pix2gestalt project demonstrates impressive innovation！However,I have encountered an issue while running the pix2gestalt project, and I would appreciate your guidance.

Here is a brief description of the problem:

①Frontend Issue: After interacting with the interface, I received an "Error" message on the frontend (please see the attached screenshot for reference). It seems to occur when I run the "pix2gestalt" operation.
②Backend Log: Interestingly, the backend does not report any error. Everything seems to execute as expected, with the DDIM sampler reaching 100% without issues (screenshot also attached).
Could you kindly help me understand what might be causing the error on the frontend while the backend shows no sign of failure? Is there a specific step I might be missing, or could this be related to certain dependencies or settings?

Thank you for your time and assistance!
![前端](https://github.com/user-attachments/assets/fe85c682-f861-4fee-8b4a-b8e0e5d56077)
![后端](https://github.com/user-attachments/assets/dcadc545-df15-4a74-90b9-e0d3745151f5)

**Comment by egeozguroglu** [comment]
Hi, this is likely a dependency issue, with `gradio` specifically. Did you follow our installation step exactly as described?

**Comment by automate11** [comment]
Hi, thank you for your response. I have followed the installation steps and installed the necessary packages as required. However, I still couldn’t get it to run correctly on the frontend. That said, I did manage to get results by using the inference feature directly from the project.
Also, I really appreciate your thoughtfulness in using gradio to provide an intuitive interface for users. It shows great consideration for your audience. Thanks again for open-sourcing the project and for the detailed documentation!

**Comment by thousanddrowned** [comment]
> Hi, thank you for your response. I have followed the installation steps and installed the necessary packages as required. However, I still couldn’t get it to run correctly on the frontend. That said, I did manage to get results by using the inference feature directly from the project.您好，感谢您的回复。我已经按照安装步骤进行了操作，并安装了所需的包。然而，我仍然无法在前端正确运行它。话虽如此，我确实通过直接从项目中使用推理功能得到了结果。 Also, I really appreciate your thoughtfulness in using gradio to provide an intuitive interface for users. It shows great consideration for your audience. Thanks again for open-sourcing the project and for the detailed documentation!此外，我非常欣赏您使用 gradio 为用户提供直观界面的周到考虑。这显示了您对受众的极大关注。再次感谢您开源此项目以及详细的文档！

How to get results without gradio, could you help me please?
