### ISSUE TITLE
pix2gestalt的gradio界面报错

### ISSUE THREAD

**Issue by zyypostgrduate** [cvlab-columbia/pix2gestalt#26]
![微信图片_20241119154546](https://github.com/user-attachments/assets/8d62537b-5328-4a9b-90b1-cdb793c7317f)

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0
Running DDIM Sampling with 199 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00,  6.92it/s]
Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0
Running DDIM Sampling with 199 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00,  6.91it/s]
Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0
Running DDIM Sampling with 99 timesteps
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00,  6.90it/s]

Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0
Running DDIM Sampling with 99 timesteps
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00,  6.93it/s]
Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0
Running DDIM Sampling with 99 timesteps
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s]

Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0
Running DDIM Sampling with 99 timesteps
DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s]
没有报错，为什么SAM阶段也能生成visible mask，为啥pix2gestalt阶段gradio界面就显示error呢,

**Comment by egeozguroglu** [comment]
Hi, did you follow our installation steps as described?

**Comment by egeozguroglu** [comment]
Marking as resolved for now, it's likely that your Gradio version was incorrect.

**Comment by ghost** [comment]
> Marking as resolved for now, it's likely that your Gradio version was incorrect.

I have encountered the same problem, what is the correct gradio version? Or is the generated image already saved locally for us to view?

**Comment by egeozguroglu** [comment]
> > Marking as resolved for now, it's likely that your Gradio version was incorrect.
> 
> I have encountered the same problem, what is the correct gradio version? Or is the generated image already saved locally for us to view?

Check out the [requirements.txt](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/requirements.txt)

**Comment by ghost** [comment]
> > > Marking as resolved for now, it's likely that your Gradio version was incorrect.
> > 
> > 
> > I have encountered the same problem, what is the correct gradio version? Or is the generated image already saved locally for us to view?
> 
> Check out the [requirements.txt](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/requirements.txt)
The installed version is exactly gradio==3.41.0 as stated in the requirements.txt, but the above situation will still occur.

**Comment by thousanddrowned** [comment]
> > > > Marking as resolved for now, it's likely that your Gradio version was incorrect.标记为当前已解决，很可能你的 Gradio 版本不正确。
> > > 
> > > 
> > > I have encountered the same problem, what is the correct gradio version? Or is the generated image already saved locally for us to view?我遇到了相同的问题，正确的 gradio 版本是什么？或者生成的图片已经保存到本地，我们可以查看吗？
> > 
> > 
> > Check out the [requirements.txt](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/requirements.txt)查看 requirements.txt
> > The installed version is exactly gradio==3.41.0 as stated in the requirements.txt, but the above situation will still occur.已安装的版本与 requirements.txt 中声明的完全一致，即 gradio==3.41.0，但上述情况仍然会发生。

The same problems, did you solve it?

**Comment by seulqxq** [comment]
> ![微信图片_20241119154546](https://github.com/user-attachments/assets/8d62537b-5328-4a9b-90b1-cdb793c7317f)
> 
> This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces) Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 199 timesteps DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00, 6.92it/s] Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 199 timesteps DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00, 6.91it/s] Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00, 6.90it/s]
> 
> Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00, 6.93it/s] Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s]
> 
> Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s] 没有报错，为什么SAM阶段也能生成visible mask，为啥pix2gestalt阶段gradio界面就显示error呢,

The same problems, did you solve it?

**Comment by zyypostgrduate** [comment]
可能是你的内存不够大，所以没法生成amodal mask


一生钟意
***@***.***



        



         原始邮件
         
       
发件人：Seul ***@***.***&gt;
发件时间：2025年11月17日 11:45
收件人：cvlab-columbia/pix2gestalt ***@***.***&gt;
抄送：zyypostgrduate ***@***.***&gt;, Author ***@***.***&gt;
主题：Re: [cvlab-columbia/pix2gestalt] pix2gestalt的gradio界面报错 (Issue #26)



seulqxq left a comment (cvlab-columbia/pix2gestalt#26)

_20241119154546.png (view on web)

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run gradio deploy&nbsp;from Terminal to deploy to Spaces (https://huggingface.co/spaces) Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 199 timesteps DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00, 6.92it/s] Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 199 timesteps DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00, 6.91it/s] Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00, 6.90it/s]

Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00, 6.93it/s] Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s]

Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s] 没有报错，为什么SAM阶段也能生成visible mask，为啥pix2gestalt阶段gradio界面就显示error呢,

The same problems, did you solve it?

**Comment by seulqxq** [comment]
> 可能是你的内存不够大，所以没法生成amodal mask
> 
> 
> 一生钟意
> ***@***.***
> 
> 
> 
> 
> 
> 
> 
>          原始邮件
> 
> 
> 发件人：Seul ***@***.***&gt;
> 发件时间：2025年11月17日 11:45
> 收件人：cvlab-columbia/pix2gestalt ***@***.***&gt;
> 抄送：zyypostgrduate ***@***.***&gt;, Author ***@***.***&gt;
> 主题：Re: [cvlab-columbia/pix2gestalt] pix2gestalt的gradio界面报错 (Issue [#26](https://github.com/cvlab-columbia/pix2gestalt/issues/26))
> 
> 
> 
> seulqxq left a comment ([cvlab-columbia/pix2gestalt#26](https://github.com/cvlab-columbia/pix2gestalt/issues/26))
> 
> _20241119154546.png (view on web)
> 
> This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run gradio deploy&nbsp;from Terminal to deploy to Spaces (https://huggingface.co/spaces) Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 199 timesteps DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00, 6.92it/s] Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 199 timesteps DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:28<00:00, 6.91it/s] Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00, 6.90it/s]
> 
> Data shape for DDIM sampling is (4, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:14<00:00, 6.93it/s] Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s]
> 
> Data shape for DDIM sampling is (2, 4, 32, 32), eta 1.0 Running DDIM Sampling with 99 timesteps DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:08<00:00, 11.94it/s] 没有报错，为什么SAM阶段也能生成visible mask，为啥pix2gestalt阶段gradio界面就显示error呢,
> 
> The same problems, did you solve it?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

好的，我再去尝试一下，感谢你的回复
