### ISSUE TITLE
Inference 

### ISSUE THREAD

**Issue by Glaciercoool** [cvlab-columbia/pix2gestalt#27]
Can the 3090 24G directly perform inference?

**Comment by egeozguroglu** [comment]
Hi, you may likely need two 3090 GPUs (parallelized). The released Gradio demo typically requires 26GB. We've tested it on A6000s and A100s.

**Comment by Glaciercoool** [comment]
thank u very much~

**Comment by Haodong-Yan** [comment]
> thank u very much~

Have try run it on two gpus? can you provide your script？

**Comment by egeozguroglu** [comment]
Hi! You can do something along [this script](https://gist.github.com/egeozguroglu/7ed8dc6b344ae6b2d21d28542a55d877) to parallelize. It is simply using torch.multiprocessing's spawn & the functions we released in [inference.py](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/inference.py). Note that this script isn't extensively cleaned up. Please let me know if any further questions!

**Comment by ghost** [comment]
> Hi! You can do something along [this script](https://gist.github.com/egeozguroglu/7ed8dc6b344ae6b2d21d28542a55d877) to parallelize. It is simply using torch.multiprocessing's spawn & the functions we released in [inference.py](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/inference.py). Note that this script isn't extensively cleaned up. Please let me know if any further questions!

How can I run this script? Can you give an example? Can this just input one picture and inference?

**Comment by ghost** [comment]
Also，I meet an error:  
from eval.amodal_coco.amodalAPI.PythonAPI.pycocotools.amodal import Amodal 
ModuleNotFoundError: No module named 'eval'

**Comment by egeozguroglu** [comment]
Hi, that script is simply an example for parallelization (for Amodal COCO eval) you can use to implement your own. We're happy to release a separate script on the repo if that would help.

**Comment by ghost** [comment]
> Hi, that script is simply an example for parallelization (for Amodal COCO eval) you can use to implement your own. We're happy to release a separate script on the repo if that would help.

If I want to run gradio distributed, which file should I change? Thank you
