### ISSUE TITLE
Depth Completion

### ISSUE THREAD

**Issue by ThePassedWind** [cvlab-columbia/pix2gestalt#28]
Nice work!
I want to ask if there is a way to add corresponding depth completion based on your model?

**Comment by egeozguroglu** [comment]
Hi, you can simply run your go-to depth completion on pix2gestalt outputs, similar to our recognition, novel-view-synthesis, and 3D reconstruction experiments. Our method can be used as a drop-in module to significantly improve the performance of existing depth estimators (in the presence of occlusions).

After performing amodal completion, any off-the-shelf depth method will work.
