### ISSUE TITLE
Seeking the original images for the dataset

### ISSUE THREAD

**Issue by liuzc1999** [cvlab-columbia/pix2gestalt#29]
In the dataset released now, the occluded images, the whole images, and the visible/amodal masks are accessible, while the original images without the synthesized occlusion are not included. If possible, could you consider adding the corresponding original images to the dataset? For such an inspiring dataset, I believe covering this additional paired data would further enhance its versatility to support more tasks. Thanks a lot for your consideration!

**Comment by egeozguroglu** [comment]
Hi, that's intentional. Since the original images are sourced from the [SA-1B dataset](https://ai.meta.com/datasets/segment-anything-downloads/), they can directly be retrieved using the indices/IDs we released.

**Comment by liuzc1999** [comment]
Oh, I see! Thanks : )
