### ISSUE TITLE
The parameters in the config file

### ISSUE THREAD

**Issue by zhahuohua** [cvlab-columbia/pix2gestalt#33]
Hello, author. I am currently trying to run the run_pix2gestalt module to complete a single image, but the backend shows that it still requires 25,357 MB of memory. Is this the correct memory usage in this case? If not, could you please let me know if there are any parameters in the config file（sd-finetune-pix2gestalt-c_concat-256.yaml） or other files **that I can adjust to reduce memory usage**? Thank you.

**Comment by egeozguroglu** [comment]
Yes, that's correct.
