### ISSUE TITLE
Demo or Inference code

### ISSUE THREAD

**Issue by dqj5182** [cvlab-columbia/pix2gestalt#5]
May I ask how we can demo or do inference on custom image (meaning our own image)?

Also, I wish to ask what is computational burden for running inference of the model on GPU.

**Comment by egeozguroglu** [comment]
Hi, you can find instructions and computational requirements [here](https://github.com/cvlab-columbia/pix2gestalt?tab=readme-ov-file#inference-and-weights).

**Comment by dqj5182** [comment]
Oh. I think I failed to find the section.
I'll try it out!
