### ISSUE TITLE
config.json file missing from HF

### ISSUE THREAD

**Issue by lange4531** [cvlab-columbia/pix2gestalt#7]
Hi there! 

When will you be releasing the config.json file?

**Comment by egeozguroglu** [comment]
Hi, our training and fine-tuning config was released [here](https://github.com/cvlab-columbia/pix2gestalt/blob/main/pix2gestalt/configs/sd-finetune-pix2gestalt-c_concat-256.yaml).  

You don't need an additional config.json for Huggingface. Please follow our Gradio demo, which is self-sufficient for [inference](https://github.com/cvlab-columbia/pix2gestalt?tab=readme-ov-file#inference-and-weights).  Does this clarify? Feel free to follow up with any further questions.
